USE `cegepjon_p2019-dev`;

INSERT INTO Rarete(nomRarete) VALUES 
('Commun'), ('Rare'), ('Épique'), ('Légendaire');
INSERT INTO Categorie(nomCategorie) VALUES 
('Objets de carte'), ('Cadres de carte'), ('Caractéristiques'), ('Évolution');
INSERT INTO Ressource(nomRessource, categorie, rarete, description, lienImage, ressourceUnique, statut) VALUES 
('Rattata', 1, 1, 'Pokémon Normal', '/ObjetsCarte/Rattata', false, 'ACT'),
('Pidgey', 1, 1, 'Pokémon Vol', '/ObjetsCarte/Pidgey', false, 'ACT'),
('Caterpie', 1, 1, 'Pokémon Insecte', '/ObjetsCarte/Caterpie', false, 'ACT'),
('Ekans', 1, 1, 'Pokémon Poison', '/ObjetsCarte/Ekans', false, 'ACT'),
('Bulbasaur', 1, 2, 'Pokémon Plante', '/ObjetsCarte/Bulbasaur', false, 'ACT'),
('Eevee', 1, 2, 'Pokémon Normal', '/ObjetsCarte/Eevee', false, 'ACT'),
('Charmander', 1, 2, 'Pokémon Feu', '/ObjetsCarte/Charmander', false, 'ACT'),
('Squirtle', 1, 2, 'Pokémon Eau', '/ObjetsCarte/Squirtle', false, 'ACT'),
('Clefairy', 1, 3, 'Pokémon Fée', '/ObjetsCarte/Clefairy', false, 'ACT'),
('Togepi', 1, 3, 'Pokémon Fée', '/ObjetsCarte/Togepi', false, 'ACT'),
('Ditto', 1, 3, 'Pokémon Normal', '/ObjetsCarte/Ditto', false, 'ACT'),
('Jynx', 1, 3, 'Pokémon Glace', '/ObjetsCarte/Jynx', false, 'ACT'),
('Mew', 1, 4, 'Pokémon Psy', '/ObjetsCarte/Mew', false, 'ACT'),
('Mewtwo', 1, 4, 'Pokémon Psy', '/ObjetsCarte/Mewtwo', false, 'ACT'),
('Articuno', 1, 4, 'Pokémon Glace', '/ObjetsCarte/Articuno', false, 'ACT'),
('Moltres', 1, 4, 'Pokémon Feu', '/ObjetsCarte/Moltres', false, 'ACT'),
('Zapdos', 1, 4, 'Pokémon Électrik', '/ObjetsCarte/Zapdos', false, 'ACT'),
('Plante', 2, 1, 'Cadre simple aux couleurs du type Plante', '/CadresCarte/CadrePlante', false, 'ACT'),
('Feu', 2, 1, 'Cadre simple aux couleurs du type Feu', '/CadresCarte/CadreFeu', false, 'ACT'),
('Eau', 2, 1, 'Cadre simple aux couleurs du type Eau', '/CadresCarte/CadreEau', false, 'ACT'),
('Insecte', 2, 1, 'Cadre simple aux couleurs du type Insecte', '/CadresCarte/CadreInsecte', false, 'ACT'),
('Électrik', 2, 2, 'Cadre aux couleurs du type Électrik', '/CadresCarte/CadreÉlectrik', false, 'ACT'),
('Glace', 2, 2, 'Cadre aux couleurs du type Glace', '/CadresCarte/CadreGlace', false, 'ACT'),
('Poison', 2, 2, 'Cadre aux couleurs du type Poison', '/CadresCarte/CadrePoison', false, 'ACT'),
('Sol', 2, 2, 'Cadre aux couleurs du type Sol', '/CadresCarte/CadreSol', false, 'ACT'),
('Psy', 2, 3, 'Beau cadre aux couleurs du type Psy', '/CadresCarte/CadrePsy', false, 'ACT'),
('Vol', 2, 3, 'Beau cadre aux couleurs du type Vol', '/CadresCarte/CadreVol', false, 'ACT'),
('Combat', 2, 3, 'Beau cadre aux couleurs du type Combat', '/CadresCarte/CadreCombat', false, 'ACT'),
('Acier', 2, 3, 'Beau cadre aux couleurs du type Acier', '/CadresCarte/CadreAcier', false, 'ACT'),
('Ténèbres', 2, 4, 'Magnifique cadre aux couleurs du type Ténèbres', '/CadresCarte/CadreTenebres', false, 'ACT'),
('Spectre', 2, 4, 'Magnifique cadre aux couleurs du type Spectre', '/CadresCarte/CadreSpectre', false, 'ACT'),
('Dragon', 2, 4, 'Magnifique cadre aux couleurs du type Dragon', '/CadresCarte/CadreDragon', false, 'ACT'),
('Fée', 2, 4, 'Magnifique cadre aux couleurs du type Fée', '/CadresCarte/CadreFee', false, 'ACT'),
('Résistance Feu 1', 3, 1, 'Résistance au feu de niveau 1', '/Caracteristiques/ResistanceFeu1', false, 'ACT'),
('Résistance Eau 1', 3, 1, 'Résistance à l\'eau de niveau 1', '/Caracteristiques/ResistanceEau1', false, 'ACT'),
('Résistance Plante 1', 3, 1, 'Résistance aux plantes de niveau 1', '/Caracteristiques/ResistancePlante1', false, 'ACT'),
('Résistance Glace 1', 3, 1, 'Résistance à la glace de niveau 1', '/Caracteristiques/ResistanceGlace1', false, 'ACT'),
('Résistance Feu 2', 3, 2, 'Résistance au feu de niveau 2', '/Caracteristiques/ResistanceFeu2', false, 'ACT'),
('Résistance Eau 2', 3, 2, 'Résistance à l\'eau de niveau 2', '/Caracteristiques/ResistanceEau2', false, 'ACT'),
('Résistance Plante 2', 3, 2, 'Résistance aux plantes de niveau 2', '/Caracteristiques/ResistancePlante2', false, 'ACT'),
('Résistance Glace 2', 3, 2, 'Résistance à la glace de niveau 2', '/Caracteristiques/ResistanceGlace2', false, 'ACT'),
('Résistance Feu 3', 3, 3, 'Résistance au feu de niveau 3', '/Caracteristiques/ResistanceFeu3', false, 'ACT'),
('Résistance Eau 3', 3, 3, 'Résistance à l\'eau de niveau 3', '/Caracteristiques/ResistanceEau3', false, 'ACT'),
('Résistance Plante 3', 3, 3, 'Résistance aux plantes de niveau 3', '/Caracteristiques/ResistancePlante3', false, 'ACT'),
('Résistance Glace 3', 3, 3, 'Résistance à la glace de niveau 3', '/Caracteristiques/ResistanceGlace3', false, 'ACT'),
('Résistance Feu 4', 3, 4, 'Résistance au feu de niveau 4', '/Caracteristiques/ResistanceFeu4', false, 'ACT'),
('Résistance Eau 4', 3, 4, 'Résistance à l\'eau de niveau 4', '/Caracteristiques/ResistanceEau4', false, 'ACT'),
('Résistance Plante 4', 3, 4, 'Résistance aux plantes de niveau 4', '/Caracteristiques/ResistancePlante4', false, 'ACT'),
('Résistance Glace 4', 3, 4, 'Résistance à la glace de niveau 4', '/Caracteristiques/ResistanceGlace4', false, 'ACT'),
('Wartortle Eau', 4, 1, 'Évolution Eau de Squirtle', '/Evolution/WartortleEau', false, 'ACT'),
('Wartortle Feu', 4, 1, 'Évolution Feu de Squirtle', '/Evolution/WartortleFeu', false, 'ACT'),
('Wartortle Glace', 4, 1, 'Évolution Glace de Squirtle', '/Evolution/WartortleGlace', false, 'ACT'),
('Wartortle Plante', 4, 1, 'Évolution Plante de Squirtle', '/Evolution/WartortlePlante', false, 'ACT'),
('Ivysaur Eau', 4, 1, 'Évolution Eau de Bubasaur', '/Evolution/IvysaurEau', false, 'ACT'),
('Ivysaur Feu', 4, 1, 'Évolution Feu de Bulbasaur', '/Evolution/IvysaurFeu', false, 'ACT'),
('Ivysaur Glace', 4, 1, 'Évolution Glace de Bulbasaur', '/Evolution/IvysaurGlace', false, 'ACT'),
('Ivysaur Plante', 4, 1, 'Évolution Plante de Bulbasaur', '/Evolution/IvysaurPlante', false, 'ACT'),
('Charmeleon Eau', 4, 1, 'Évolution Eau de Charmander', '/Evolution/CharmeleonEau', false, 'ACT'),
('Charmeleon Feu', 4, 1, 'Évolution Feu de Charmander', '/Evolution/CharmeleonFeu', false, 'ACT'),
('Charmeleon Glace', 4, 1, 'Évolution Glace de Charmander', '/Evolution/CharmeleonGlace', false, 'ACT'),
('Charmeleon Plante', 4, 1, 'Évolution Plante de Charmander', '/Evolution/CharmeleonPlante', false, 'ACT');

INSERT INTO RareteCategorieRessource(noRarete, noCategorie, prix) VALUES
(1, 1, 10), (1, 2, 15), (1, 3, 20), (1, 4, 25),
(2, 1, 5), (2, 2, 10), (2, 3, 15), (2, 4, 20),
(3, 1, 15), (3, 2, 20), (3, 3, 25), (3, 4, 30),
(4, 1, 25), (4, 2, 30), (4, 3, 35), (4, 4, 40);